### ISSUE TITLE
Compiled .whl file ?

### ISSUE THREAD

**Issue by Igor-Shabalin** [nathtest/Tutorial-Ubuntu-18.04-Install-Nvidia-driver-and-CUDA-and-CUDNN-and-build-Tensorflow-for-gpu#2]
Friend! For several days I have been trying to build tensorflow according to your instructions. I get different errors. Could you post the finished .whl file? I would be very grateful to you.

**Comment by nathtest** [comment]
Hi Igor-Shabalin, the purpose of compiling tensorflow is to match the compute capabilities of your gpu card and is specific to your system.
So i cannot provide you a .whl. 
You could use the prebuilt version of tensorflow-gpu or look on the official tensorflow github issue to find your compilation errors.

**Comment by Igor-Shabalin** [comment]
I have, like you, a video card Geforce 740M, ubuntu 18.04 and an Intel 7 CPU. Prebuilt version of tensorflow-gpu do not work for me because they have capabilities of 3.5. I can’t build it from the sources with GPU support, I get different errors when compiling with different versions of drivers and/or bazel. Maybe you still share the whl file? I will be very grateful to you.
